version: '3.8'
services:
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=sumdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/
    ports:
      - '5431:5432'

